### ISSUE TITLE
ImportError: cannot import name 'abs'

### ISSUE THREAD

**Issue by wqq19930507** [huoyijie/AdvancedEAST#18]
请问遇到过这个问题吗，是版本不匹配吗？麻烦赐教

**Comment by wqq19930507** [comment]
非常感谢您的回复，通过anaconda搭建python=3.6.5的虚拟环境，tensorflow-gpu=1.5,numpy=1.14.1,tqdm=4.19.7
pip install keras 版本为2.2.2
Using TensorFlow backend.
Traceback (most recent call last):
  File "predict.py", line 5, in <module>
    from keras.preprocessing import image
  File "/home/wangqiqi1/anaconda3/envs/tensorflow1.5/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/wangqiqi1/anaconda3/envs/tensorflow1.5/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/home/wangqiqi1/anaconda3/envs/tensorflow1.5/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/home/wangqiqi1/anaconda3/envs/tensorflow1.5/lib/python3.6/site-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/home/wangqiqi1/anaconda3/envs/tensorflow1.5/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 6, in <module>
    from tensorflow.python.framework import ops as tf_ops
ModuleNotFoundError: No module named 'tensorflow.python.framework'

**Comment by wqq19930507** [comment]
该问题已解决，在测试时遇到一个问题，麻烦您不吝赐教
Traceback (most recent call last):
  File "predict.py", line 149, in <module>
    east_detect.load_weights(cfg.saved_model_weights_file_path)
  File "/home/wangqiqi1/anaconda3/envs/tensorflow1.5/lib/python3.6/site-packages/Keras-2.2.2-py3.6.egg/keras/engine/network.py", line 1163, in load_weights
  File "/home/wangqiqi1/anaconda3/envs/tensorflow1.5/lib/python3.6/site-packages/Keras-2.2.2-py3.6.egg/keras/engine/saving.py", line 900, in load_weights_from_hdf5_group
ValueError: You are trying to load a weight file containing 58 layers into a model with 30 layers.

**Comment by huoyijie** [comment]
昨天修复网络部分bug，网络层数变了，我重新训练一个模型文件再上传下，可以用来测试看看

**Comment by wqq19930507** [comment]
非常感谢，若重新上传了，麻烦告知一下

**Comment by huoyijie** [comment]
链接: https://pan.baidu.com/s/1KO7tR_MW767ggmbTjIJpuQ 密码: kpm2
