### ISSUE TITLE
版主帮我看看可以么？谢谢了

### ISSUE THREAD

**Issue by mialrr** [huoyijie/AdvancedEAST#26]
/usr/bin/python3.5 /home/louj1/pywork/AEAST/advanced_east.py
Using TensorFlow backend.
2018-08-31 16:23:45.429362: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-08-31 16:23:45.539453: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-31 16:23:45.539777: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212] Found device 0 with properties: 
name: TITAN Xp COLLECTORS EDITION major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 11.90GiB freeMemory: 11.53GiB
2018-08-31 16:23:45.620421: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-31 16:23:45.620734: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212] Found device 1 with properties: 
name: TITAN Xp COLLECTORS EDITION major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:02:00.0
totalMemory: 11.90GiB freeMemory: 11.74GiB
2018-08-31 16:23:45.621578: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1227] Device peer to peer matrix
2018-08-31 16:23:45.621598: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1233] DMA: 0 1 
2018-08-31 16:23:45.621603: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1243] 0:   Y Y 
2018-08-31 16:23:45.621605: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1243] 1:   Y Y 
2018-08-31 16:23:45.621610: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1312] Adding visible gpu devices: 0, 1
2018-08-31 16:23:45.947115: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11167 MB memory) -> physical GPU (device: 0, name: TITAN Xp COLLECTORS EDITION, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-08-31 16:23:46.041544: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 11364 MB memory) -> physical GPU (device: 1, name: TITAN Xp COLLECTORS EDITION, pci bus id: 0000:02:00.0, compute capability: 6.1)
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_img (InputLayer)          (None, None, None, 3 0                                            
__________________________________________________________________________________________________
block1_conv1 (Conv2D)           (None, None, None, 6 1792        input_img[0][0]                  
__________________________________________________________________________________________________
block1_conv2 (Conv2D)           (None, None, None, 6 36928       block1_conv1[0][0]               
__________________________________________________________________________________________________
block1_pool (MaxPooling2D)      (None, None, None, 6 0           block1_conv2[0][0]               
__________________________________________________________________________________________________
block2_conv1 (Conv2D)           (None, None, None, 1 73856       block1_pool[0][0]                
__________________________________________________________________________________________________
block2_conv2 (Conv2D)           (None, None, None, 1 147584      block2_conv1[0][0]               
__________________________________________________________________________________________________
block2_pool (MaxPooling2D)      (None, None, None, 1 0           block2_conv2[0][0]               
__________________________________________________________________________________________________
block3_conv1 (Conv2D)           (None, None, None, 2 295168      block2_pool[0][0]                
__________________________________________________________________________________________________
block3_conv2 (Conv2D)           (None, None, None, 2 590080      block3_conv1[0][0]               
__________________________________________________________________________________________________
block3_conv3 (Conv2D)           (None, None, None, 2 590080      block3_conv2[0][0]               
__________________________________________________________________________________________________
block3_pool (MaxPooling2D)      (None, None, None, 2 0           block3_conv3[0][0]               
__________________________________________________________________________________________________
block4_conv1 (Conv2D)           (None, None, None, 5 1180160     block3_pool[0][0]                
__________________________________________________________________________________________________
block4_conv2 (Conv2D)           (None, None, None, 5 2359808     block4_conv1[0][0]               
__________________________________________________________________________________________________
block4_conv3 (Conv2D)           (None, None, None, 5 2359808     block4_conv2[0][0]               
__________________________________________________________________________________________________
block4_pool (MaxPooling2D)      (None, None, None, 5 0           block4_conv3[0][0]               
__________________________________________________________________________________________________
block5_conv1 (Conv2D)           (None, None, None, 5 2359808     block4_pool[0][0]                
__________________________________________________________________________________________________
block5_conv2 (Conv2D)           (None, None, None, 5 2359808     block5_conv1[0][0]               
__________________________________________________________________________________________________
block5_conv3 (Conv2D)           (None, None, None, 5 2359808     block5_conv2[0][0]               
__________________________________________________________________________________________________
block5_pool (MaxPooling2D)      (None, None, None, 5 0           block5_conv3[0][0]               
__________________________________________________________________________________________________
up_sampling2d_3 (UpSampling2D)  (None, None, None, 5 0           block5_pool[0][0]                
__________________________________________________________________________________________________
concatenate_3 (Concatenate)     (None, None, None, 1 0           up_sampling2d_3[0][0]            
                                                                 block4_pool[0][0]                
__________________________________________________________________________________________________
batch_normalization_2 (BatchNor (None, None, None, 1 4096        concatenate_3[0][0]              
__________________________________________________________________________________________________
conv2d_1 (Conv2D)               (None, None, None, 1 131200      batch_normalization_2[0][0]      
__________________________________________________________________________________________________
batch_normalization_3 (BatchNor (None, None, None, 1 512         conv2d_1[0][0]                   
__________________________________________________________________________________________________
conv2d_2 (Conv2D)               (None, None, None, 1 147584      batch_normalization_3[0][0]      
__________________________________________________________________________________________________
up_sampling2d_2 (UpSampling2D)  (None, None, None, 1 0           conv2d_2[0][0]                   
__________________________________________________________________________________________________
concatenate_2 (Concatenate)     (None, None, None, 3 0           up_sampling2d_2[0][0]            
                                                                 block3_pool[0][0]                
__________________________________________________________________________________________________
batch_normalization_4 (BatchNor (None, None, None, 3 1536        concatenate_2[0][0]              
__________________________________________________________________________________________________
conv2d_3 (Conv2D)               (None, None, None, 6 24640       batch_normalization_4[0][0]      
__________________________________________________________________________________________________
batch_normalization_5 (BatchNor (None, None, None, 6 256         conv2d_3[0][0]                   
__________________________________________________________________________________________________
conv2d_4 (Conv2D)               (None, None, None, 6 36928       batch_normalization_5[0][0]      
__________________________________________________________________________________________________
up_sampling2d_1 (UpSampling2D)  (None, None, None, 6 0           conv2d_4[0][0]                   
__________________________________________________________________________________________________
concatenate_1 (Concatenate)     (None, None, None, 1 0           up_sampling2d_1[0][0]            
                                                                 block2_pool[0][0]                
__________________________________________________________________________________________________
batch_normalization_6 (BatchNor (None, None, None, 1 768         concatenate_1[0][0]              
__________________________________________________________________________________________________
conv2d_5 (Conv2D)               (None, None, None, 3 6176        batch_normalization_6[0][0]      
__________________________________________________________________________________________________
batch_normalization_7 (BatchNor (None, None, None, 3 128         conv2d_5[0][0]                   
__________________________________________________________________________________________________
conv2d_6 (Conv2D)               (None, None, None, 3 9248        batch_normalization_7[0][0]      
__________________________________________________________________________________________________
batch_normalization_1 (BatchNor (None, None, None, 3 128         conv2d_6[0][0]                   
__________________________________________________________________________________________________
conv2d_7 (Conv2D)               (None, None, None, 3 9248        batch_normalization_1[0][0]      
__________________________________________________________________________________________________
inside_score (Conv2D)           (None, None, None, 1 33          conv2d_7[0][0]                   
__________________________________________________________________________________________________
side_vertex_code (Conv2D)       (None, None, None, 2 66          conv2d_7[0][0]                   
__________________________________________________________________________________________________
side_vertex_coord (Conv2D)      (None, None, None, 4 132         conv2d_7[0][0]                   
__________________________________________________________________________________________________
east_detect (Concatenate)       (None, None, None, 7 0           inside_score[0][0]               
                                                                 side_vertex_code[0][0]           
                                                                 side_vertex_coord[0][0]          
==================================================================================================
Total params: 15,087,367
Trainable params: 15,083,655
Non-trainable params: 3,712
__________________________________________________________________________________________________
Epoch 1/24
Traceback (most recent call last):
  File "/home/louj1/pywork/AEAST/advanced_east.py", line 31, in <module>
    verbose=1)])
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training_generator.py", line 177, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py", line 658, in _data_generator_task
    generator_output = next(self._generator)
  File "/home/louj1/pywork/AEAST/data_generator.py", line 37, in gen
    y[i] = np.load(gt_file)
ValueError: could not broadcast input array from shape (21,4,2) into shape (64,64,7)

Process finished with exit code 1
![6240a56e-7950-412d-9981-6b56fd7c8a79](https://user-images.githubusercontent.com/19602341/44902828-90dfda80-ad3d-11e8-994d-c6e7b337812a.png)

**Comment by huoyijie** [comment]
训练主要有3个步骤，均需按照顺序执行，你是不是没有执行preprocess和label处理?
#1. 对数据进行预处理 python preprocess.py
#2. 对数据进行标注处理 python label.py
#3. 开始训练 python advanced_east.py

**Comment by huoyijie** [comment]
label.py会把经过标注的数据按照numpy格式写入文件，然后再data_generator.py中进行读取产生训练数据。这个是错误是说读取的gt文件数据维度和训练所需要（cfg.py中配置）的维度不匹配。你仔细check下cfg.py中配置，然后依次运行上面的3个步骤。
