### ISSUE TITLE
validation_steps=None

### ISSUE THREAD

**Issue by theimpossibledream** [huoyijie/AdvancedEAST#49]
@huoyijie 

```
(east) home@home-lnx:~/Desktop/program/AdvancedEAST$ python advanced_east.py
Using TensorFlow backend.
2019-02-11 18:44:57.258140: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
2019-02-11 18:44:57.259110: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
.
.
.
.
==================================================================================================
Total params: 15,087,367
Trainable params: 15,083,655
Non-trainable params: 3,712
__________________________________________________________________________________________________
WARNING:tensorflow:Variable *= will be deprecated. Use `var.assign(var * other)` if you want assignment to the variable value or `x = x * y` if you want a new python Tensor object.
Traceback (most recent call last):
  File "advanced_east.py", line 31, in <module>
    verbose=1)])
  File "/home/home/anaconda3/envs/east/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/home/anaconda3/envs/east/lib/python3.6/site-packages/keras/engine/training.py", line 2115, in fit_generator
    raise ValueError('`validation_steps=None` is only valid for a'
ValueError: `validation_steps=None` is only valid for a generator based on the `keras.utils.Sequence` class. Please specify `validation_steps` or use the `keras.utils.Sequence` class.
```

**Comment by Tocv-lx** [comment]
遇到过这个问题，检查了一下发现是验证集数据太少，小于batchsize，所以求出validation_steps=0。你可以检查一下是不是这个问题

**Comment by snowwindy** [comment]
你好，想问一下，是不是只要看训练阶段的损失值就可以了？可以看到验证集的准确率吗？
